import { User, QuizPackage, SubmissionRecord } from './types';

export const INITIAL_CLASSES = [
  'Kelas 1 SD',
  'Kelas 2 SD',
  'Kelas 3 SD',
  'Kelas 4 SD',
  'Kelas 5 SD',
  'Kelas 6 SD',
];

export const SD_SUBJECTS = [
  'IPAS (Ilmu Pengetahuan Alam & Sosial)',
  'Matematika SD',
  'Bahasa Indonesia',
  'Pendidikan Pancasila',
  'Seni Budaya & Prakarya (SBdP)',
  'Pendidikan Agama Islam (PAI)',
  'PJOK',
];

// Initially ONLY ADMIN exists. NO guru accounts until generated by Admin!
export const INITIAL_USERS: User[] = [
  {
    id: 'user-admin-rudi',
    name: 'Rudi Mulyana, S.Pd',
    username: 'rudimulyana72',
    password: 'yunamaura28',
    role: 'ADMIN',
    email: 'rudimulyana72@guru.sd.belajar.id',
    nipOrNis: '198204122008011005',
    subject: 'Kepala Kurikulum & Administrator SD',
    createdAt: '2026-01-01T08:00:00Z',
  },
];

// Curated Educational Images for Elementary School (SD)
export const SAMPLE_IMAGES = [
  {
    url: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=800&q=80',
    caption: 'Struktur Daun Hijau & Proses Fotosintesis Tumbuhan (IPAS)',
  },
  {
    url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    caption: 'Rantai Makanan & Ekosistem Hutan Alam (IPAS)',
  },
  {
    url: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=80',
    caption: 'Bangun Datar Geometri & Pecahan Berhitung (Matematika SD)',
  },
  {
    url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    caption: 'Siklus Air & Presipitasi Hujan di Bumi (IPAS SD)',
  },
  {
    url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    caption: 'Karya Seni Budaya Kolase & Ragam Hias Tradisional (SBdP)',
  },
];

// Initial published packages start empty until the generated Guru creates them!
export const INITIAL_PACKAGES: QuizPackage[] = [];

// Initial submissions start empty
export const INITIAL_SUBMISSIONS: SubmissionRecord[] = [];

// Ready-made SD Template for quick generation by teachers
export const SD_QUIZ_TEMPLATE: Omit<QuizPackage, 'id' | 'teacherId' | 'teacherName'> = {
  title: 'Penilaian Harian IPAS: Bagian Tumbuhan, Fotosintesis & Ekosistem',
  subject: 'IPAS (Ilmu Pengetahuan Alam & Sosial)',
  targetClass: 'Kelas 5 SD',
  instructions:
    'Hai anak-anak hebat! Bacalah setiap pertanyaan dengan teliti ya. Perhatikan gambar tumbuhan dan ekosistem yang terlampir. Kerjakan dengan jujur dan gembira!',
  durationMinutes: 35,
  passingScore: 75,
  images: [SAMPLE_IMAGES[0].url, SAMPLE_IMAGES[1].url, SAMPLE_IMAGES[3].url],
  imageCaptions: [
    SAMPLE_IMAGES[0].caption,
    SAMPLE_IMAGES[1].caption,
    SAMPLE_IMAGES[3].caption,
  ],
  status: 'published',
  createdAt: '2026-03-01T08:00:00Z',
  publishedAt: '2026-03-01T08:05:00Z',
  aiValidation: {
    isValid: true,
    scoreQuality: 98,
    readinessStatus: 'SIAP_DISTRIBUSIKAN',
    summary:
      'Paket soal IPAS Kelas 5 SD ramah anak, memuat 5 jenis soal terstruktur lengkap dengan bahasa komunikatif, 3 lampiran ilustrasi edukatif, dan rubrik essay berjenjang.',
    recommendations: [
      'Format soal sangat sesuai untuk capaian pembelajaran fase C Sekolah Dasar.',
      'Lampiran 3 gambar di bawah kuota maksimal 5 gambar.',
      'Kunci jawaban dan pasangan matching sudah diverifikasi valid.',
    ],
    imageAnalysis: [
      'Gambar 1: Daun hijau fotosintesis (relevan untuk soal nomor 1 & 2)',
      'Gambar 2: Rantai makanan ekosistem (relevan untuk soal nomor 3 essay)',
      'Gambar 3: Siklus air dan hujan (relevan untuk soal nomor 4 & 5)',
    ],
    validatedAt: '2026-03-01T08:04:30Z',
  },
  questions: [
    {
      id: 'q-sd-1',
      number: 1,
      type: 'pilihan_ganda',
      prompt:
        'Bagian tumbuhan yang berfungsi untuk menyerap air dan zat hara mineral dari dalam tanah adalah...',
      points: 20,
      options: [
        { id: 'A', text: 'Daun' },
        { id: 'B', text: 'Akar' },
        { id: 'C', text: 'Bunga' },
        { id: 'D', text: 'Buah' },
      ],
      correctKey: 'B',
    },
    {
      id: 'q-sd-2',
      number: 2,
      type: 'isian_singkat',
      prompt:
        'Zat hijau daun pada tumbuhan yang berfungsi menangkap cahaya matahari untuk proses fotosintesis disebut...',
      points: 20,
      correctAnswer: 'Klorofil',
      keywords: ['klorofil', 'zat hijau daun', 'chlorophyll'],
    },
    {
      id: 'q-sd-3',
      number: 3,
      type: 'essay',
      prompt:
        'Perhatikan Gambar 2 tentang rantai makanan di sawah! Jelaskan apa yang terjadi pada populasi ular dan burung elang jika petani membasmi seluruh populasi tikus, dan sebutkan peran tumbuhan padi dalam rantai makanan tersebut!',
      points: 20,
      rubric:
        'Rubrik Penilaian Siswa SD: (1) Menyebutkan padi sebagai produsen makanan (bobot 30%). (2) Menjelaskan bahwa jika tikus habis, ular akan kekurangan makanan dan populasinya menurun (bobot 40%). (3) Menjelaskan dampak lanjutan pada burung elang (bobot 30%). Total nilai 0-100.',
      idealAnswer:
        'Tumbuhan padi berperan sebagai produsen karena dapat membuat makanannya sendiri melalui fotosintesis. Jika seluruh tikus dibasmi, ular sawah yang memakan tikus akan kekurangan makanan sehingga populasinya menurun, dan burung elang pemakan ular juga akan terganggu kelangsungan hidupnya.',
    },
    {
      id: 'q-sd-4',
      number: 4,
      type: 'salah_benar',
      prompt:
        'Pada proses fotosintesis, tumbuhan hijau melepaskan gas oksigen yang sangat dibutuhkan manusia dan hewan untuk bernapas.',
      statement:
        'Tumbuhan hijau melepaskan gas oksigen saat proses fotosintesis yang berguna untuk pernapasan manusia dan hewan.',
      points: 20,
      correctBoolean: true,
    },
    {
      id: 'q-sd-5',
      number: 5,
      type: 'menjodohkan',
      prompt:
        'Jodohkan nama bagian tumbuhan pada Kolom A dengan fungsi utamanya pada Kolom B!',
      points: 20,
      pairs: [
        {
          id: 'p-1',
          itemA: 'Akar',
          itemB: 'Menyerap air dari tanah',
        },
        {
          id: 'p-2',
          itemA: 'Batang',
          itemB: 'Menopang tumbuhan dan menyalurkan air',
        },
        {
          id: 'p-3',
          itemA: 'Daun',
          itemB: 'Tempat memasak makanan (fotosintesis)',
        },
        {
          id: 'p-4',
          itemA: 'Bunga',
          itemB: 'Alat perkembangbiakan tumbuhan',
        },
      ],
    },
  ],
};
